#!/bin/bash
# Build the attestation-probe APK from scratch using only:
#   - javac (JDK)
#   - d8 (from Android build-tools)  → classes.dex
#   - aapt2                          → resources + manifest → resources.ap_
#   - zipalign + apksigner           → signed APK
#
# Produces: dist/attestation-test.apk
#
set -euo pipefail

# --- Config ---
JDK="${JAVA_HOME:-/usr/lib/jvm/default-java}"
SDK="${ANDROID_HOME:-$HOME/android-sdk}"
PLATFORM_API=34
BUILD_TOOLS_VER=34.0.0
BT="$SDK/build-tools/$BUILD_TOOLS_VER"
PLATFORM_JAR="$SDK/platforms/android-$PLATFORM_API/android.jar"

PROJECT_DIR="$(cd "$(dirname "$0")" && pwd)"
SRC_DIR="$PROJECT_DIR/src"
RES_DIR="$PROJECT_DIR/res"
MANIFEST="$PROJECT_DIR/AndroidManifest.xml"
OUT_DIR="$PROJECT_DIR/build"

# Where the APK lands in the web-adb-inspector repo
DEST_DIR="$(cd "$PROJECT_DIR/.." && pwd)/../dist"
DEST_APK="$DEST_DIR/attestation-test.apk"

# --- Sanity ---
for tool in "$JDK/bin/javac" "$BT/d8" "$BT/aapt2" "$BT/zipalign" "$BT/apksigner" "$PLATFORM_JAR"; do
    [[ -x "$tool" || -f "$tool" ]] || { echo "MISSING: $tool" >&2; exit 1; }
done

rm -rf "$OUT_DIR"
mkdir -p "$OUT_DIR"/{gen,classes,dex,res}

echo "[1/5] Compile Java..."
find "$SRC_DIR" -name '*.java' > "$OUT_DIR/sources.txt"
"$JDK/bin/javac" \
    -source 1.8 -target 1.8 \
    -bootclasspath "$PLATFORM_JAR" \
    -classpath "$PLATFORM_JAR" \
    -d "$OUT_DIR/classes" \
    @"$OUT_DIR/sources.txt"
echo "    $(find "$OUT_DIR/classes" -name '*.class' | wc -l) class files"

echo "[2/5] Package resources + manifest (aapt2)..."
# aapt2 link emits an unsigned APK directly — but only if -o ends in .apk and
# --proto-format isn't used. The APK contains the compiled manifest + resources.arsc.
mkdir -p "$OUT_DIR/gen"
"$BT/aapt2" compile --dir "$RES_DIR" -o "$OUT_DIR/gen/res.zip"
LINKED_APK="$OUT_DIR/linked.apk"
"$BT/aapt2" link \
    -I "$PLATFORM_JAR" \
    --manifest "$MANIFEST" \
    --min-sdk-version 24 \
    --target-sdk-version 34 \
    -o "$LINKED_APK" \
    "$OUT_DIR/gen/res.zip"

echo "[3/5] d8 → classes.dex..."
"$BT/d8" \
    --min-api 24 \
    --output "$OUT_DIR/dex" \
    $(find "$OUT_DIR/classes" -name '*.class')

echo "[4/5] Add classes.dex to APK..."
# aapt2 link produced a base APK; we just need to inject classes.dex.
UNSIGNED="$OUT_DIR/unsigned.apk"
rm -f "$UNSIGNED"
python3 - "$LINKED_APK" "$OUT_DIR/dex/classes.dex" "$UNSIGNED" <<'PY'
import sys, zipfile
src_apk, dex_path, out_apk = sys.argv[1], sys.argv[2], sys.argv[3]
with zipfile.ZipFile(src_apk, 'r') as zin, \
     zipfile.ZipFile(out_apk, 'w', zipfile.ZIP_STORED) as zout:
    for item in zin.namelist():
        if item == 'classes.dex': continue  # skip — we add ours
        zout.writestr(item, zin.read(item))
    zout.write(dex_path, 'classes.dex')
PY
rm -f "$LINKED_APK"

echo "[5/5] zipalign + sign..."
ALIGNED="$OUT_DIR/aligned.apk"
rm -f "$ALIGNED"
"$BT/zipalign" -p -f 4 "$UNSIGNED" "$ALIGNED"

# Use the debug keystore generated by Android SDK build-tools init script.
# We need a keystore — generate one if absent.
KEYSTORE="${KEYSTORE:-$HOME/.android/debug.keystore}"
mkdir -p "$(dirname "$KEYSTORE")"
if [[ ! -f "$KEYSTORE" ]]; then
    "$JDK/bin/keytool" -genkey -v -keystore "$KEYSTORE" \
        -storepass android -keypass android \
        -alias androiddebugkey -keyalg RSA -keysize 2048 -validity 10000 \
        -dname "CN=Android Debug,O=Android,C=US" 2>&1 | tail -3
fi

"$BT/apksigner" sign \
    --ks "$KEYSTORE" \
    --ks-pass pass:android \
    --key-pass pass:android \
    --ks-key-alias androiddebugkey \
    --out "$DEST_APK" \
    "$ALIGNED"

echo ""
echo "APK signed: $DEST_APK"
"$BT/apksigner" verify --print-certs "$DEST_APK" | head -5
ls -lh "$DEST_APK"
